---
title: "Syllabus for OPIM 241 Data Science - Spring 2021"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

**This syllabus is effective as of `r strftime(Sys.time(), "%A,  %B %d, %Y at %I:%M %p", tz = "America/New_York")`**

## Information at-a-glance

- **Instructors:** Marck Vaisman (marck.vaisman at georgetown.edu)
- **TA**: Doug Post (dyp6 at georgetown.eu)
- **Class Schedule:** Tuesdays 5:00 - 7:45pm (Zoom link in Canvas)
- **Website:** https://opim241.netlify.app/
- **Slack:** https://opim241.slack.com

### Course Description

If you have little to no background in data science, statistics, or programming, and you are interested in making sense of (sometimes messy) data, this course is for you! Learn to explore, visualize, analyze data, model outcomes, and make predictions, and do so in a reproducible and shareable manner. Gain experience in data collection, wrangling, and visualization, exploratory data analysis, predictive modeling, and effective communication of results while working on problems and case studies inspired by and based on real-world questions. The course will focus on the R statistical computing language. No statistical or computing background is necessary.

**By the end of the course, you will be able to:**

* Gain insights from data, reproducibly and collaboratively, using modern programming tools and techniques
* Understand the use cases of data science as a function in business decision making
* Select the appropriate modeling/analytical technique for solving different kinds of problems
* Create reproducible analysis and documents
* all of the above using the `R` programming language

### Why `R` for Data Science?

Data analysis isn’t just inference and modeling, it’s also data importing, cleaning, preparation, exploration, and visualization. R is a free and open-source, powerful, flexible, and relevant programming language that allows you to perform all of these tasks easily, supported by a very vibrant community.

## Course Resources

### Books

We will be using two books for this course that cover different parts of the material. There will be assigned readings for each class from these books. 

1. Garrett Grolemund and Hadley Wickham (2017). _R for Data Science (R4DS)_. O'Reilly Media.
1. Jared Lander (2017). _R for Everyone 2nd Edition (R4E)_. Pearson.

### Software

We will be using R and RStudio in this course. You can use R/RStudio two ways:

* Install on your laptop. Please visit https://cran.r-project.org/ and https://www.rstudio.com/products/rstudio/download/ to download and install the latest versions or R and RStudio respectively. 
* Online with RStudio Cloud ( https://rstudio.cloud/). All students will receive a link to join the course's workspace. This is free for you and provides the exact same environment for everyone, and eliminates the need to install on your laptop.

## Learning Activities and Evaluation

### Scheme

Your overall course grade will be comprised of the following components:

* Homework: 40%
* Labs: 20%
* Quizzes: 10%
* Project: 30%

### Activities

### Lectures & In-Class Labs

Every class meeting will consist of a mix of lecture and interactive coding exercises that we will do together.

### Data Analysis Project (30%)

Further details on the project will be provided by the second week of class.

### Homework (40%)

To learn how to code, one must spend time coding. To aid in your learning process, we will have several problem sets, where we will apply skills learned in the class.

### Labs (20%)

Labs are a part of class. We will start labs in almost every session, and you must complete the labs after class if we don't finish them.

### Quizzes (10%)

Short quizzes will ensure you are keeping up with the material. Quizzes are meant to be brief and will take approximately 10 minutes during class.

Total is 100%. There is no plan to curve or adjust the final grade. Grading will follow official McDonough Policies.

## Policies & Expectations


### Grading

Some assignments are code-based, some are qualitative, and some are a mix of both. Grading is generally holistic, meaning that there may be no specific point value for individual elements of a deliverable. Each deliverable submission is unique and will be compared to all other submissions. 

**For code-based assignments:**

* We will look at the results files and/or scripts. If the result files are exactly what is expected, in the proper format, etc., we may run your scripts to make sure they produce the output. If everything works, you will get full credit for the problem.
* If the submitted results are not what is expected, we will look at and run your code and provide partial credit wherever possible and applicable.

**For qualitative/open-ended assignments:**

* If a deliverable exceeds the requirements and expectations, that is considered **A level** work.
* If a deliverable just meets the requirements and expectations, that is considered **A-/B+ level** work.
* If a deliverable does not meet the requirements, that is considered **B or lower level** work.

**Points will be deducted for any of the following reasons:**

* The instructions are not followed
* There are missing sections in the deliverable
* The overall presentation and/or writing is sloppy
* There are no comments in your code
* There are files in the repository other than those requested
* The repository structure is altered in any way
* Files are named incorrectly (wrong extensions, wrong case, etc.)

### No Late Deliverables

  - There are no extensions to due dates unless there are extraordinary circumstances, and those will be determined on a case-by-case basis. If you miss a quiz, lab, or assignment, you will receive a grade of 0 (zero).
  - I realize life gets in the way sometimes and you may not be able to come to class or complete an assignment/lab on time. Therefore, in lieu of a late policy, I will allow you to drop your lowest quiz grades, lowest lab grade, and lowest assignment grade. This gives you flexibility if you have to miss class (not take the quiz and/or do the lab) or cannot do an assignment for some reason. **This does not apply to the Final project**

### Online Zoom Rules

  - Please participate and speak while on Zoom. I know it's harder to do classes over Zoom, and I love participation. Ask questions. Make comments. Challenge me. If I speak for almost three hours in a silent classroom, it is a lot more boring and tiring for everyone.
  - Focus your attention on the class. Online classes require a higher level of engagement for everyone. Don't multitask (you know what we mean...)
  - Turn on your camera. If you have a bad hair day, that's ok, I do too. My preference is to see you. If you have bandwidth issues and can't use your camera, I understand.

### Communication

  - All announcements will be posted on Canvas/Slack
  - We have set up a Slack channel for communication and collaboration. Please use this tool for any question you may have about the course, assignments, or any technical issue. This way everyone can learn from each other's questions. The instructional team will be monitoring and providing answers on a regular basis. [See the collaboration rules](#rules) to know what is allowed in Slack
  - Individual emails containing any question that is not personal will not be answered

### Open Door Policy

Please approach or get in touch with us if something is not working for you regarding the class, methods, etc. Our pledge to you is to provide the best learning experience possible. If you have any issues please do not wait until the last minute to speak with us. You will find that we are fair, reasonable, and flexible and we deeply care about your success.


## Academic Integrity and Collaboration

All students are expected to maintain the highest standards of academic and personal integrity in pursuit of their education at Georgetown. **Academic dishonesty in any form is a serious offense, and students found in violation are subject to academic penalties that include but are not limited to: a reduction/zeroing of assignment grade, a reduction/zeroing of the course, immediate failure of the course.**  All students are held to the Georgetown University Honor Code. For more information about the Honor Code see [https://honorcouncil.georgetown.edu/]().

I have **ZERO-TOLERANCE POLICY** and if students are found to be in violation, there will be consequences, and the students will be penalized and reported.

### Collaboration Policy

Only work that is clearly assigned as teamwork should be completed collaboratively. Individual assignments must be completed individually, you may not directly share or discuss answers/code with anyone other than the instructors and tutors. You are welcome to discuss the problems in general and ask for advice.

### Sharing / reusing code

I am well aware that a huge volume of code is available on the web to solve any number of problems. Unless I explicitly tell you not to use something the course’s policy is that you may make use of any online resources (e.g. StackOverflow) but you must explicitly cite where you obtained any code you directly use (or use as inspiration). Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism and considered an Honor Code violation. On individual assignments, you may not directly share code with another student in this class, and on team assignments, you may not directly share code with another team in this class. You are welcome to discuss the problems together and ask for advice, but you may not send or make use of code from another team.

I also realize that some problems are short enough that there is a finite way of coding them, so code between students may be similar. However, all code submissions will be checked against every other students' code, and any high level of similarity between students will be investigated.

### Allowed use of Slack

The following communication and collaboration is allowed in Slack

  * The discussion of ideas and approaches to problems
  * The discussion and resolution of any technical/code issue
  * Posting/sharing code snippets (up to a few lines) for very specific things


## University Policies and Support Services

### Accommodations for students with disabilities

Students with documented disabilities have the right to specific accommodations that do not fundamentally alter the nature of the course. Please alert us should you require accommodations.

### Title IX Sexual Misconduct Statement

Please know that as faculty members we are committed to supporting survivors of sexual misconduct, including relationship violence and sexual assault. However, university policy also requires us to report any disclosures about sexual misconduct to the Title IX Coordinator, whose role is to coordinate the University’s response to sexual
misconduct.

Georgetown has a number of fully confidential professional resources who can provide support and assistance to survivors of sexual assault and other forms of sexual misconduct.

More information about campus resources and reporting sexual misconduct can be found at <http://sexualassault.georgetown.edu>
